insert into product(name) values('Black Widow');
insert into product(name) values('Superman');
insert into product(name) values('Rogue');
insert into product(name) values('Batman');
insert into product(name) values('Mr. Nice');
insert into product(name) values('Narko');
insert into product(name) values('Bombasto');
insert into product(name) values('Celeritas');
insert into product(name) values('Magneta');
insert into product(name) values('RubberMan');
insert into product(name) values('Dynama');
insert into product(name) values('Dr IQ');
insert into product(name) values('Magma');
insert into product(name) values('Tornado');
insert into product(name) values('Veronika');
insert into product(name) values('Gleb');